name: Sync master

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync master branch
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git push origin HEAD:refs/heads/master --force
